version: "3.9"

services:
  airflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sodai-airflow
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - PYTHONPATH=/opt/airflow
    volumes:
      - ./:/opt/airflow
    ports:
      - "8080:8080"
    command: >
      bash -c "
      airflow db migrate &&
      airflow users create -u admin -p admin -f Admin -l User -r Admin -e admin@example.com || true &&
      airflow webserver &
      airflow scheduler
      "